### PR TITLE
Correct invalid keywords.txt KEYWORD_TOKENTYPE

### PR DESCRIPTION
**Pull request by per1234**
Use of an invalid KEYWORD_TOKENTYPE value in keywords.txt causes the keyword to be colored by the default editor.function.style (as used by KEYWORD2, KEYWORD3, LITERAL2) in Arduino IDE 1.6.5 and newer. On Arduino IDE 1.6.4 and older this will cause the keyword to not be recognized for any special coloration.

Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keyword_tokentype

### CODE REVIEW

**Comment by CornyjK** [comment]
Thanks for your PR, I tried to convert it to newest library format, I totally missed this one!

**Comment by CornyjK** [comment]
I might request for adding ToneAC to Arduino library manager, I might ask original author first.

**Comment by per1234** [comment]
I definitely recommend doing so. Someone tried adding a fork of this particular author's NewPing library to the Library Manager index a while back and they objected (https://github.com/arduino/Arduino/issues/5798). It ended up working out well in the end because it motivated the author to add the original library.

I think they are much more active on the NewPing project so they very well might feel differently about the toneAC library.

You would always be welcome to change the `name` value in library.properties for your fork and go ahead but it's best to give the original author an opportunity to claim their original library name since every library in Library Manager index must have a unique library.properties `name` value.

It looks to me like this repository is fully compliant with the Library Manager requirements.

**Comment by CornyjK** [comment]
After reading that conversation it seems to me like he will want to add library himself, not sure about adding to @PlatformIO registry, as we would need it too (since we give ability to use both Arduino IDE and PlatformIO and we need keep those platfoms consistent).

**Comment by CornyjK** [comment]
I wrote email to teckel and he said I should create PR, so I tried (I hate BitBucket so much, GitHub seems a lot better to me). But there is problem that it seems like on BitBucket are PRs disabled by default, I wrote to him again and he didn't respond.

**Comment by per1234** [comment]
That's a shame. Thanks for making the effort to try at least!

I haven't tried a PR on BitBucket yet since there seem to be very few Arduino projects on there. I do occasionally need to review repositories on there for Library Manager compliance and it's a struggle to navigate but that may be only that I'm not used to the interface.

**Comment by CornyjK** [comment]
I think other sources than github should never been allowed.

**Comment by per1234** [comment]
It was actually teckel that caused that, though likely it would have happened anyway. I think it's good to allow choices. It's healthy for the community to have multiple good options for hosting Git projects. It keeps our Microsoft overlords on their toes a bit more. If they start doing stupid things to GitHub we might just all migrate elsewhere and their $7.5 billion purchase won't be worth much. If that happened I would likely be heading to GitLab, not BitBucket.

**Comment by CornyjK** [comment]
@per1234
I agree with you, however I don't think MS will screw GitHub, recently bought companies seems to be fine, unlike Nokia. Also keeping all things on one platform is best imo. Btw. if you will ever need anything from me (eg. review), feel free to mention me.

**Pull request merged**
